import {
  Zap,
  Crown,
  Briefcase
} from "lucide-react";

export const plans = [
  {
    id: "free",
    name: "Gratuito",
    badge: "ATUAL",
    badgeClass: "border-zinc-500/30 bg-zinc-500/10 text-zinc-400",
    price: null,
    priceAnnual: null,
    priceLabel: "Grátis para sempre",
    description: "Para quem está começando a construir sua presença online.",
    accent: "zinc",
    cardClass: "border-white/6 bg-white/2",
    buttonClass:
      "border-white/10 bg-white/5 text-zinc-400 cursor-not-allowed opacity-60",
    buttonLabel: "Plano atual",
    buttonDisabled: true,
    icon: Briefcase,
    iconClass: "text-zinc-400",
    iconBgClass: "bg-zinc-500/10",
    features: [
      { label: "1 currículo gerado ATS-friendly", included: true },
      { label: "1 análise de projeto no GitHub", included: true },
      { label: "10 adaptações de currículo para vagas", included: true },
      { label: "Portfólio Gerado e Hospedado", included: false },
      { label: "Currículo padrão nacional e internacional", included: false },
      { label: "Simulação de Entrevistas (Soft e Hard Skills)", included: false },
      { label: "Recruiter Score", included: false },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    badge: "MAIS POPULAR",
    badgeClass: "border-blue-500/30 bg-blue-500/10 text-blue-300",
    price: "R$\u00a024,99",
    priceAnnual: "R$\u00a0263,88",
    priceLabel: "/mês",
    priceLabelAnual: "/ano",
    description:
      "Para devs que querem se destacar no mercado com ferramentas completas.",
    accent: "blue",
    cardClass: "border-blue-500/25 bg-blue-500/5",
    buttonClass:
      "bg-blue-600 text-white shadow-lg shadow-blue-950/50 hover:bg-blue-500 cursor-pointer",
    buttonLabel: "Assinar Pro",
    buttonDisabled: false,
    icon: Zap,
    iconClass: "text-blue-400",
    iconBgClass: "bg-blue-500/10",
    features: [
      { label: "1 Portfólio Customizado Gerado e Hospedado", included: true },
      { label: "5 Análises completas de projeto no GitHub", included: true },
      { label: "50 adaptações de currículo para vagas", included: true },
      { label: "Currículo padrão nacional ATS-friendly", included: true },
      { label: "10 Cover Letters profissionais e customizadas", included: true },
      { label: "Simulação de Entrevistas (Soft e Hard Skills)", included: false },
      { label: "Recruiter Score", included: false },
    ],
  },
  {
    id: "career",
    name: "Career",
    badge: "COMPLETO",
    badgeClass: "border-violet-500/30 bg-violet-500/10 text-violet-300",
    price: "R$\u00a039,99",
    priceAnnual: "R$\u00a0419,88",
    priceLabel: "/mês",
    priceLabelAnual: "/ano",
    description:
      "Para quem quer a experiência completa rumo à vaga dos sonhos.",
    accent: "violet",
    cardClass: "border-violet-500/25 bg-violet-500/5",
    buttonClass:
      "bg-violet-600 text-white shadow-lg shadow-violet-950/50 hover:bg-violet-500 cursor-pointer",
    buttonLabel: "Assinar Career",
    buttonDisabled: false,
    icon: Crown,
    iconClass: "text-violet-400",
    iconBgClass: "bg-violet-500/10",
    features: [
      { label: "1 Portfólio Customizado Gerado e Hospedado", included: true },
      { label: "10 Análises completas de projeto no GitHub", included: true },
      { label: "100 adaptações de currículo para vagas", included: true },
      { label: "Currículo padrão nacional e internacional ATS-friendly", included: true },
      { label: "20 Cover Letters profissionais e customizadas", included: true },
      { label: "Simulação de Entrevistas (Soft e Hard Skills)", included: true },
      { label: "Recruiter Score", included: true },
    ],
  },
];