// Mapeamento das Linguagens de Programação por repositório
export const STACK_MAP: Record<string, string[]> = {
  TypeScript: ["TypeScript", "Node.js", "ESLint", "Prettier"],
  JavaScript: ["JavaScript (ES6+)", "Node.js", "npm"],
  Python: ["Python 3", "pip", "venv"],
  Java: ["Java", "Maven / Gradle", "JVM"],
  "C#": ["C#", ".NET", "NuGet"],
  Go: ["Go", "Go Modules"],
  Rust: ["Rust", "Cargo"],
  Ruby: ["Ruby", "Bundler"],
  PHP: ["PHP", "Composer"],
  Swift: ["Swift", "SPM", "Xcode"],
  Kotlin: ["Kotlin", "Gradle", "JVM"],
  SQL: ["SQL", "PostgreSQL", "MySQL"],
  Dart: ["Dart", "Flutter", "pub"],
  Scala: ["Scala", "sbt", "Akka"],
  Shell: ["Shell", "Bash", "POSIX"],
  R: ["R", "CRAN", "tidyverse"],
  Vue: ["Vue", "JavaScript/TypeScript", "Vite / Vue CLI", "Nuxt.js"],
  React: ["React", "JavaScript/TypeScript", "Vite / Create React App"],
  "Next.js": ["Next.js", "React", "Vercel"],
  Express: ["Node.js", "Express", "npm"],
  Django: ["Python", "Django", "pip"],
  "Spring Boot": ["Java", "Spring Boot", "Maven / Gradle"],
};